### ISSUE TITLE
add (Currency Type) as a parameter to the payment creation function

### ISSUE THREAD

**Issue by hamakh11** [rawahamid/laravel-fib-integration#3]
FibPayment::create($amount, $description) function should also have (currency type).

**Comment by rawahamid** [comment]
Sorry but till now FIB only supports IQD and this is written in there documentation so we don't have to added now because its not working

**FIB documentation screenshot**
<img width="1054" alt="Screenshot 2023-05-05 at 7 51 09 PM" src="https://user-images.githubusercontent.com/27570598/236518970-6fa1671d-83dc-4e3b-adaa-07f8610001e3.png">

**Comment by hamakh11** [comment]
ah yes, you are right, I will close the issue
